import type { Metadata } from "next";
import "./globals.css";
import SidebarWrapper from "./(components)/sidebarWrapper";
import ClientProvider from "./clientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <SidebarWrapper>{children}</SidebarWrapper>
        </ClientProvider>
      </body>
    </html>
  );
}
